### ISSUE TITLE
zabbix-ldap-sync donot delete user

### ISSUE THREAD

**Issue by albenstein** [dnaeon/zabbix-ldap-sync#12] opened 2016-02-24 13:20 UTC
We're now using zabbix-ldap-sync on our system and we like it. But if we delete user on LDAP, zabbix-ldap-sync donot delete user on zabbix system. Could you please add this feature?
Thanks.

**Comment by dnaeon** [comment] 2016-02-24 14:45
Hey @albenstein,

That would be nice to have, unfortunately it's not as simple as it looks like.

First off, there's no way we can tell that a user in Zabbix is a local user or a user coming from LDAP, which makes it harder to pick accounts which are for deletion.

We can get the accounts which are missing in LDAP and present in Zabbix, which could be good candidates for removal, but the problem is that this would also match builtin or locally added accounts as well, e.g. `Administator` account.

I'll leave the issue open, but I don't expect to be ready with it soon.

**Comment by dfisek** [comment] 2016-02-25 07:44
Can't we add some sort of flag to the accounts that are created via LDAP to seperate them from local accounts?

On the other hand in some installation the administrator may want to work around the problem you state by simply not using any local accounts, thus gaining the ability to delete synced users.

So, what I'm saying is, we can make this an optional feature, with the fair warning that any local users created will be deleted when this feature is used.

**Comment by dnaeon** [comment] 2016-02-25 08:52
@dfisek, please feel free to send a PR that we can discuss on how to approach this one.

Thanks!

**Comment by dnaeon** [comment] 2016-05-26 15:09
Fixed in #21

**Closed by dnaeon** 2016-05-26 15:09 UTC
